name: apt
description: |
  Installs the mentioned apt packages.
author: KOLANICH

inputs:
  packagesNamesFile:
    description: 'A path to a file containing names of apt packages.'
    required: false
    default: './.ci/aptPackagesToInstall.txt'

runs:
  using: "composite"
  steps:
    - run: bash ${{github.action_path}}/action.sh ${{inputs.packagesNamesFile}}
      shell: bash  # fuck, this doesn't guarantee that the script is called with bash. Has to call bash explicitly

branding:
  icon: package
  color: green
